apiVersion: v2
name: erpnext
description: Kubernetes Helm Chart for the latest stable ERPNext branch
icon: https://raw.githubusercontent.com/frappe/erpnext/develop/erpnext/public/images/erpnext-logo.png
type: application
version: 7.0.120
appVersion: v15.38.0
dependencies:
- name: redis
  condition: redis-cache.enabled
  alias: redis-cache
  version: "17.15.2"
  repository: https://charts.bitnami.com/bitnami
- name: redis
  condition: redis-queue.enabled
  alias: redis-queue
  version: "17.15.2"
  repository: https://charts.bitnami.com/bitnami
- name: mariadb
  condition: mariadb.enabled
  version: "11.5.7"
  repository: https://charts.bitnami.com/bitnami
- name: postgresql
  condition: postgresql.enabled
  version: "12.1.6"
  repository: https://charts.bitnami.com/bitnami
