apiVersion: v2
name: erpnext
description: Kubernetes Helm Chart for the latest stable ERPNext branch
icon:
  https://raw.githubusercontent.com/frappe/erpnext/develop/erpnext/public/images/erpnext-logo.png
type: application
version: 7.0.244
appVersion: v15.83.0
dependencies:
- name: dragonfly
  condition: dragonfly-cache.enabled
  alias: dragonfly-cache
  version: "v1.34.2"
  repository: "oci://ghcr.io/dragonflydb/dragonfly/helm"
- name: dragonfly
  condition: dragonfly-queue.enabled
  alias: dragonfly-queue
  version: "v1.34.2"
  repository: "oci://ghcr.io/dragonflydb/dragonfly/helm"
- name: postgresql
  condition: postgresql.enabled
  version: "12.1.6"
  repository: https://charts.bitnami.com/bitnami
