apiVersion: v2
name: erpnext
description: Kubernetes Helm Chart for the latest stable ERPNext branch
icon: 
  https://raw.githubusercontent.com/frappe/erpnext/develop/erpnext/public/images/erpnext-logo.png
type: application
version: 8.0.12
appVersion: v15.93.2
dependencies:
- name: mariadb
  condition: mariadb.enabled,mariadb-subchart.enabled
  alias: mariadb-subchart
  version: "11.5.7"
  repository: "https://charts.bitnami.com/bitnami"
- name: postgresql
  condition: postgresql.enabled,postgresql-subchart.enabled
  alias: postgresql-subchart
  version: "12.1.6"
  repository: "https://charts.bitnami.com/bitnami"
- name: redis
  condition: redis-cache.enabled
  alias: redis-cache
  version: "17.15.2"
  repository: "https://charts.bitnami.com/bitnami"
- name: redis
  condition: redis-queue.enabled
  alias: redis-queue
  version: "17.15.2"
  repository: "https://charts.bitnami.com/bitnami"
- name: dragonfly
  condition: dragonfly-cache.enabled
  alias: dragonfly-cache
  version: "v1.34.2"
  repository: "oci://ghcr.io/dragonflydb/dragonfly/helm"
- name: dragonfly
  condition: dragonfly-queue.enabled
  alias: dragonfly-queue
  version: "v1.34.2"
  repository: "oci://ghcr.io/dragonflydb/dragonfly/helm"
