{{- if or (and .Values.dbRootPassword (not .Values.dbExistingSecret)) .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "erpnext.fullname" . }}
type: Opaque
stringData:
  {{- if .Values.mariadb.enabled }}
  mariadb-root-password: {{ .Values.mariadb.rootPassword | quote }}
  {{- end }}
  {{- if .Values.dbRootPassword }}
  db-root-password: {{ .Values.dbRootPassword | b64enc | quote }}
  {{- end }}
{{- end }}
