{{- if or (and .Values.dbRootPassword (not .Values.dbExistingSecret)) (and (index .Values "mariadb-sts").enabled (index .Values "mariadb-sts").rootPassword) (and (index .Values "postgresql-sts").enabled (index .Values "postgresql-sts").postgresPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "erpnext.fullname" . }}
type: Opaque
stringData:
  {{- if and (index .Values "postgresql-sts").enabled (index .Values "postgresql-sts").postgresPassword }}
  postgres-password: {{ (index .Values "postgresql-sts").postgresPassword | quote }}
  {{- end }}
  {{- if and (index .Values "mariadb-sts").enabled (index .Values "mariadb-sts").rootPassword }}
  mariadb-root-password: {{ (index .Values "mariadb-sts").rootPassword | quote }}
  {{- end }}
  {{- if and .Values.dbRootPassword (not .Values.dbExistingSecret) }}
  db-root-password: {{ .Values.dbRootPassword | quote }}
  {{- end }}
{{- end }}
