{{- if or (and .Values.dbRootPassword (not .Values.dbExistingSecret)) (and .Values.mariadb.enabled .Values.mariadb.rootPassword) (and .Values.postgresql.enabled .Values.postgresql.postgresPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "erpnext.fullname" . }}
type: Opaque
stringData:
  {{- if and .Values.postgresql.enabled .Values.postgresql.postgresPassword }}
  postgres-password: {{ .Values.postgresql.postgresPassword | quote }}
  {{- end }}
  {{- if and .Values.mariadb.enabled .Values.mariadb.rootPassword }}
  mariadb-root-password: {{ .Values.mariadb.rootPassword | quote }}
  {{- end }}
  {{- if and .Values.dbRootPassword (not .Values.dbExistingSecret) }}
  db-root-password: {{ .Values.dbRootPassword | quote }}
  {{- end }}
{{- end }}
