{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "erpnext.fullname" . }}-postgresql
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/name: {{ include "erpnext.name" . }}-postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
