{{- if .Values.mariadb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "erpnext.fullname" . }}-mariadb
  labels:
    {{- include "erpnext.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "erpnext.name" . }}-mariadb
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "erpnext.fullname" . }}-mariadb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "erpnext.name" . }}-mariadb
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mariadb
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "erpnext.fullname" . }}
                  key: mariadb-root-password
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.mariadb.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            {{- if .Values.mariadb.myCnf }}
            - name: config
              mountPath: /etc/mysql/conf.d/my.cnf
              subPath: my.cnf
            {{- end }}
      volumes:
        {{- if .Values.mariadb.myCnf }}
        - name: config
          configMap:
            name: {{ include "erpnext.fullname" . }}-mariadb
        {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.mariadb.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.mariadb.persistence.size }}
{{- end }}
