apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erpnext
  namespace: argocd
spec:
  destination:
    namespace: erpnext
    server: https://kubernetes.default.svc
  source:
    path: erpnext
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
